imports:
    - { resource: '../../tests/fixtures/shop_configuration.yaml' }
    - { resource: '../../tests/fixtures/product_attributes.yaml' }
    - { resource: '../../tests/fixtures/product_options.yaml' }
    - { resource: '../../tests/fixtures/taxons.yaml' }
    - { resource: '../../tests/fixtures/pizza_products.yaml' }